# Development MySQL Profile Configuration
# OpenESPI Authorization Server - MySQL Development Environment

spring:
  # MySQL Database Configuration
  datasource:
    url: jdbc:mysql://localhost:3306/oauth2_authserver?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:openespi_user}
    password: ${DB_PASSWORD:openespi_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 300000
      max-lifetime: 1200000
      auto-commit: false
  
  # JPA/Hibernate Configuration for MySQL
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
        connection:
          characterEncoding: utf8
          CharSet: utf8
          useUnicode: true
  
  # Flyway Migration for MySQL
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/mysql
    schemas: oauth2_authserver
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}

# Development Logging
logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.greenbuttonalliance.espi: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.mysql: INFO
  file:
    name: logs/authserver-dev-mysql.log

# Development Server Configuration
server:
  error:
    include-stacktrace: always
    include-message: always

# OAuth2 Development Settings
espi:
  oauth2:
    # Development clients (will be moved to database)
    clients:
      datacustodian:
        client-id: data_custodian_admin
        client-secret: dev_secret_dc
        base-url: http://localhost:8080
      thirdparty:
        client-id: third_party
        client-secret: dev_secret_tp  
        base-url: http://localhost:9090
    # JWT Development Settings
    jwt:
      access-token-validity: PT6H    # 6 hours
      refresh-token-validity: PT24H  # 24 hours