# NAESB ESPI 4.0 Specific Configuration
# TLS 1.3 Only Configuration for Maximum Security Compliance

server:
  port: ${SERVER_PORT:8443}
  servlet:
    context-path: /
  # NAESB ESPI 4.0 Mandatory TLS 1.3 Configuration
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH:classpath:keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: ${SSL_KEY_ALIAS:espi-authserver}
    protocol: TLSv1.3
    enabled-protocols: TLSv1.3
    # NAESB ESPI 4.0 Approved Cipher Suites ONLY
    ciphers: TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256
    # Perfect Forward Secrecy (PFS) Settings
    client-auth: ${SSL_CLIENT_AUTH:none}
    trust-store: ${SSL_TRUSTSTORE_PATH:}
    trust-store-password: ${SSL_TRUSTSTORE_PASSWORD:}
    trust-store-type: PKCS12
    # TLS 1.3 Specific Settings
    key-store-provider: ${SSL_KEYSTORE_PROVIDER:}
    trust-store-provider: ${SSL_TRUSTSTORE_PROVIDER:}

spring:
  application:
    name: openespi-authorization-server-espi40
  
  profiles:
    active: espi40
  
  # Security Configuration - NAESB ESPI 4.0 Compliance
  security:
    oauth2:
      authorizationserver:
        issuer: ${OAUTH2_ISSUER:https://localhost:8443}
        endpoint:
          authorization-uri: /oauth2/authorize
          token-uri: /oauth2/token
          jwk-set-uri: /oauth2/jwks
          token-revocation-uri: /oauth2/revoke
          token-introspection-uri: /oauth2/introspect
    # Force HTTPS with TLS 1.3 for all security operations
    require-ssl: true
    headers:
      # Enhanced HSTS for NAESB ESPI 4.0
      frame-options: DENY
      content-type-options: nosniff
      xss-protection: 1; mode=block
      http-strict-transport-security:
        max-age: 63072000  # 2 years for ESPI 4.0
        include-subdomains: true
        preload: true
  
  # Database Configuration - TLS 1.3 Required
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/oauth2_authserver?useSSL=true&requireSSL=true&verifyServerCertificate=true&tlsVersions=TLSv1.3&sslMode=REQUIRED&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC}
    username: ${DATABASE_USERNAME:oauth2_user}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 900000
      leak-detection-threshold: 30000
      # Additional security settings
      connection-test-query: SELECT 1
      validation-timeout: 5000

# ESPI 4.0 Specific Configuration
espi:
  version: "4.0"
  compliance: "NAESB ESPI 4.0"
  
  # Security settings - TLS 1.3 Only
  security:
    require-https: true
    require-https-redirect-uris: true
    tls-version: "1.3"
    allowed-cipher-suites:
      - TLS_AES_256_GCM_SHA384
      - TLS_CHACHA20_POLY1305_SHA256  
      - TLS_AES_128_GCM_SHA256
    perfect-forward-secrecy: true
    certificate-validation: required
    
  # Token settings - ESPI 4.0 Requirements
  token:
    format: opaque  # REQUIRED for ESPI 4.0
    access-token-lifetime: PT6H   # 6 hours maximum
    refresh-token-lifetime: PT72H # 72 hours maximum
    authorization-code-lifetime: PT5M # 5 minutes maximum
    
  # Client settings
  client:
    require-authorization-consent: true
    require-pkce: true  # ESPI 4.0 recommendation
    max-redirect-uris: 3
    allowed-grant-types:
      - authorization_code
      - refresh_token
      - client_credentials
    # Forbidden grant types in ESPI 4.0
    forbidden-grant-types:
      - implicit
      - password
      - device_code

# Logging Configuration - Security Focused
logging:
  level:
    root: WARN
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    org.springframework.security.oauth2.server.authorization: INFO
    org.greenbuttonalliance.espi: INFO
    # TLS/SSL Debugging (disable in production)
    javax.net.ssl: ${SSL_DEBUG_LEVEL:WARN}
    org.apache.tomcat.util.net: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE_PATH:/var/log/openespi/espi40-authorization-server.log}

# Management Endpoints - Secured for ESPI 4.0
management:
  endpoints:
    web:
      exposure:
        include: health,info
      base-path: /actuator
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      show-details: never  # Security hardening
    info:
      enabled: true
  server:
    port: ${MANAGEMENT_PORT:8444}
    ssl:
      enabled: true
  security:
    enabled: true
    
# Application Information - ESPI 4.0
info:
  app:
    name: OpenESPI Authorization Server - NAESB ESPI 4.0
    description: Green Button Alliance OAuth2 Authorization Server - NAESB ESPI 4.0 Compliant
    version: '@project.version@'
    environment: espi40-production
    espi:
      version: "4.0"
      compliance: "NAESB ESPI 4.0 Standard"
      security-level: maximum
      tls-version: "TLSv1.3-only"
      cipher-suites: "TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256"
      perfect-forward-secrecy: true
      certificate-validation: required
      
# External Service Configuration - All TLS 1.3
external:
  greenbuttondata:
    base-url: ${GBD_BASE_URL:https://services.greenbuttondata.org}
    tls-version: TLSv1.3
    cipher-suites: TLS_AES_256_GCM_SHA384,TLS_CHACHA20_POLY1305_SHA256,TLS_AES_128_GCM_SHA256
    
  gba-registry:
    base-url: ${GBA_REGISTRY_URL:https://registry.greenbuttonalliance.org}
    tls-version: TLSv1.3
    certificate-validation: required

# Session Configuration - Enhanced Security
server:
  servlet:
    session:
      cookie:
        secure: true
        http-only: true
        same-site: strict
        max-age: PT30M  # 30 minutes
      timeout: PT30M
      # Enhanced session security
      tracking-modes: cookie  # No URL rewriting
      
# NAESB ESPI 4.0 Specific Validation Rules
validation:
  redirect-uris:
    require-https: true
    allow-localhost-http: false  # Strict production mode
    max-length: 2048
    allowed-schemes: [https]
    forbidden-patterns:
      - javascript:
      - data:
      - file:
      - ftp:
      
  client-registration:
    require-client-name: true
    min-client-name-length: 3
    max-client-name-length: 255
    require-contact-email: true
    max-redirect-uris: 3
    
  scopes:
    validate-espi-format: true
    allowed-espi-versions: ["4.0"]
    require-function-block: true