/*
 *
 *        Copyright (c) 2025 Green Button Alliance, Inc.
 *
 *
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 *
 */

package org.greenbuttonalliance.espi.common;

import com.fasterxml.jackson.annotation.JsonInclude;
import org.greenbuttonalliance.espi.common.dto.atom.AtomEntryDto;
import org.greenbuttonalliance.espi.common.dto.usage.UsagePointDto;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import tools.jackson.databind.AnnotationIntrospector;
import tools.jackson.databind.SerializationFeature;
import tools.jackson.databind.cfg.DateTimeFeature;
import tools.jackson.databind.introspect.JacksonAnnotationIntrospector;
import tools.jackson.databind.util.StdDateFormat;
import tools.jackson.dataformat.xml.XmlAnnotationIntrospector;
import tools.jackson.dataformat.xml.XmlMapper;
import tools.jackson.dataformat.xml.XmlWriteFeature;
import tools.jackson.module.jakarta.xmlbind.JakartaXmlBindAnnotationIntrospector;
import tools.jackson.module.jakarta.xmlbind.JakartaXmlBindAnnotationModule;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Debug test to see what XML is actually generated by Jackson 3 XmlMapper.
 * Useful for validating XML structure and namespace handling.
 */
@DisplayName("XML Debug Test")
class XmlDebugTest {

    private XmlMapper xmlMapper;

    @BeforeEach
    void setUp() {
        // Initialize Jackson 3 XmlMapper with JAXB annotation support
        AnnotationIntrospector intr = XmlAnnotationIntrospector.Pair.instance(
            new JakartaXmlBindAnnotationIntrospector(),
            new JacksonAnnotationIntrospector()
        );

        xmlMapper = XmlMapper.xmlBuilder()
            .annotationIntrospector(intr)
            .addModule(new JakartaXmlBindAnnotationModule()
                .setNonNillableInclusion(JsonInclude.Include.NON_EMPTY))
            .enable(SerializationFeature.INDENT_OUTPUT)
            .enable(DateTimeFeature.WRITE_DATES_WITH_ZONE_ID)
            .disable(XmlWriteFeature.WRITE_NULLS_AS_XSI_NIL)
            .defaultDateFormat(new StdDateFormat())
            .build();
    }

    @Test
    @DisplayName("Debug: See what XML is actually generated by Jackson 3")
    void debugXmlOutput() throws Exception {
        // Create a simple UsagePointDto
        UsagePointDto usagePoint = new UsagePointDto(
            "urn:uuid:debug-test",
            new byte[]{0x01}, // Simple role flag
            null, // serviceCategory
            (short) 1, // Active status
            null, null, null, null, null, // serviceDeliveryPoint, amiBillingReady, checkBilling, connectionState, estimatedLoad
            null, null, null, null, // grounded, isSdp, isVirtual, minimalUsageExpected
            null, null, null, null, null, // nominalServiceVoltage, outageRegion, phaseCode, ratedCurrent, ratedPower
            null, null, null, null, // readCycle, readRoute, serviceDeliveryRemark, servicePriority
            null, null, null, null, null // pnodeRefs, aggregatedNodeRefs, meterReadings, usageSummaries, electricPowerQualitySummaries
        );

        // Wrap in Atom entry with description as title (IdentifiedObject fields handled by Atom layer)
        AtomEntryDto entry = new AtomEntryDto("urn:uuid:debug-test", "Debug Service", usagePoint);

        // Marshal to XML using Jackson 3
        String xml = xmlMapper.writeValueAsString(entry);

        // Print the actual XML for debugging
        System.out.println("Generated XML (Jackson 3):");
        System.out.println("==========================");
        System.out.println(xml);
        System.out.println("==========================");

        // Comprehensive assertions
        assertThat(xml).isNotNull();
        assertThat(xml.trim()).isNotEmpty();

        // Validate root element
        assertThat(xml).contains("entry"); // Now wrapping in Atom entry
        assertThat(xml).contains("UsagePoint");

        // Validate ESPI namespace
        assertThat(xml).contains("http://naesb.org/espi");

        // Validate content
        assertThat(xml).contains("Debug Service"); // In Atom title
        assertThat(xml).containsPattern("<status[^>]*>1</status>");
        assertThat(xml).contains("01"); // roleFlags as hex

        // Validate XML structure - now wrapped in Atom entry
        assertThat(xml).contains("<entry");
        assertThat(xml).contains("<title>Debug Service</title>");
        assertThat(xml).contains("</entry>");

        // Validate no utility methods are serialized (should have @XmlTransient)
        assertThat(xml).doesNotContain("meterReadingCount");
        assertThat(xml).doesNotContain("usageSummaryCount");
        assertThat(xml).doesNotContain("generateSelfHref");
        assertThat(xml).doesNotContain("generateUpHref");
    }

    @Test
    @DisplayName("Debug: Complex UsagePoint with all fields")
    void debugComplexUsagePoint() throws Exception {
        // Create UsagePoint with more fields populated
        UsagePointDto usagePoint = new UsagePointDto(
            "urn:uuid:complex-test",
            new byte[]{0x01, 0x02, 0x03, 0x04},
            null, // serviceCategory
            (short) 2,
            null, null, null, null, null,
            null, null, null, null,
            null, null, null, null, null,
            null, null, null, null,
            null, null, null, null, null
        );

        // Wrap in Atom entry with description as title (IdentifiedObject fields handled by Atom layer)
        AtomEntryDto entry = new AtomEntryDto("urn:uuid:complex-test", "Complex Service with Special & Characters <test>", usagePoint);

        // Marshal to XML using Jackson 3
        String xml = xmlMapper.writeValueAsString(entry);

        // Print for debugging
        System.out.println("\nComplex XML (Jackson 3):");
        System.out.println("========================");
        System.out.println(xml);
        System.out.println("========================\n");

        // Validate XML escaping
        assertThat(xml).contains("&amp;"); // & is escaped
        assertThat(xml).contains("&lt;"); // < is escaped

        // Validate hex encoding of roleFlags
        assertThat(xml).contains("01020304");

        // Validate structure - description in Atom title
        assertThat(xml).contains("Complex Service with Special &amp; Characters &lt;test>");
        assertThat(xml).contains("<entry");
        assertThat(xml).contains("</entry>");
    }

    @Test
    @DisplayName("Debug: Minimal UsagePoint (mostly nulls)")
    void debugMinimalUsagePoint() throws Exception {
        // Create minimal UsagePoint
        UsagePointDto usagePoint = new UsagePointDto(
            "urn:uuid:minimal-test", // uuid
            null, // roleFlags
            null, // serviceCategory
            null, // status
            null, null, null, null, null, // serviceDeliveryPoint, amiBillingReady, checkBilling, connectionState, estimatedLoad
            null, null, null, null, // grounded, isSdp, isVirtual, minimalUsageExpected
            null, null, null, null, null, // nominalServiceVoltage, outageRegion, phaseCode, ratedCurrent, ratedPower
            null, null, null, null, // readCycle, readRoute, serviceDeliveryRemark, servicePriority
            null, null, null, null, null // pnodeRefs, aggregatedNodeRefs, meterReadings, usageSummaries, electricPowerQualitySummaries
        );

        // Wrap in Atom entry with null title (IdentifiedObject fields handled by Atom layer)
        AtomEntryDto entry = new AtomEntryDto("urn:uuid:minimal-test", null, usagePoint);

        // Marshal to XML using Jackson 3
        String xml = xmlMapper.writeValueAsString(entry);

        // Print for debugging
        System.out.println("\nMinimal XML (Jackson 3):");
        System.out.println("========================");
        System.out.println(xml);
        System.out.println("========================\n");

        // Validate minimal structure
        assertThat(xml).contains("entry"); // Now wrapping in Atom entry
        assertThat(xml).contains("UsagePoint");
        assertThat(xml).contains("http://naesb.org/espi");

        // Validate that null fields are not included (NON_EMPTY policy)
        assertThat(xml).doesNotContain("<description"); // Still no description in content
        assertThat(xml).doesNotContain("<roleFlags");
    }
}
