# Local Development H2 Profile Configuration
spring:
  datasource:
    url: jdbc:h2:mem:datacustodian;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      pool-name: DataCustodianHikariCP
      auto-commit: false
  
  h2:
    console:
      enabled: ${H2_CONSOLE_ENABLED:true}  # Set to false in production
      path: /h2-console
      settings:
        web-allow-others: false  # Security: Never allow remote access
        trace: false
        web-admin-password: ${H2_ADMIN_PASSWORD:}  # Require password for admin access
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        generate_statistics: true
        
  flyway:
    enabled: false  # Disable Flyway for H2 development

# Development-specific logging
logging:
  level:
    org.greenbuttonalliance.espi: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  
server:
  port: 8081

espi:
  datacustodian:
    base-url: http://localhost:8081/DataCustodian
  authorization-server:
    issuer-uri: http://localhost:9999
    introspection-endpoint: http://localhost:9999/oauth2/introspect
    client-id: data_custodian_admin
    client-secret: secret