/*
 *
 *        Copyright (c) 2025 Green Button Alliance, Inc.
 *
 *
 *     Licensed under the Apache License, Version 2.0 (the "License");
 *     you may not use this file except in compliance with the License.
 *     You may obtain a copy of the License at
 *
 *         http://www.apache.org/licenses/LICENSE-2.0
 *
 *     Unless required by applicable law or agreed to in writing, software
 *     distributed under the License is distributed on an "AS IS" BASIS,
 *     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *     See the License for the specific language governing permissions and
 *     limitations under the License.
 *
 */

package org.greenbuttonalliance.espi.common.domain.usage;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotNull;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.proxy.HibernateProxy;
import org.hibernate.type.SqlTypes;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
import java.util.UUID;

/**
 * Pure JPA/Hibernate entity for Subscription without JAXB concerns.
 *
 * Defines the parameters of a subscription between Third Party and Data
 * Custodian. Represents a formal agreement allowing third-party applications
 * to access specific usage points and energy data for a retail customer.
 *
 * <p>Key characteristics:</p>
 * <ul>
 *   <li>Application-specific entity (NOT an ESPI standard resource)</li>
 *   <li>Uses UUID for primary key (indexed for API access)</li>
 *   <li>Links OAuth2 Authorization to accessible UsagePoints</li>
 *   <li>Does NOT extend IdentifiedObject (no selfLink/upLink in database)</li>
 *   <li>Atom Feed output handled by DTO layer with dynamic links</li>
 * </ul>
 */
@Entity
@Table(name = "subscriptions", indexes = {
    @Index(name = "idx_subscription_retail_customer", columnList = "retail_customer_id"),
    @Index(name = "idx_subscription_application", columnList = "application_information_id"),
    @Index(name = "idx_subscription_authorization", columnList = "authorization_id")
})
@Getter
@Setter
@NoArgsConstructor
public class SubscriptionEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     * UUID primary key for API access.
     * Subscription is an application-specific entity, not an ESPI resource,
     * but uses UUID for consistent API patterns.
     */
    @Id
    @JdbcTypeCode(SqlTypes.CHAR)
    @Column(length = 36, columnDefinition = "char(36)", updatable = false, nullable = false)
    private UUID id;

    /**
     * Optional hashed identifier for external references.
     * Used for privacy and security in external communications.
     */
    @Column(name = "hashed_id", length = 64)
    private String hashedId;

    /**
     * Retail customer who owns this subscription.
     * The customer whose data is being accessed through this subscription.
     */
    @ManyToOne(cascade = CascadeType.DETACH, fetch = FetchType.LAZY)
    @JoinColumn(name = "retail_customer_id")
    @NotNull
    private RetailCustomerEntity retailCustomer;

    /**
     * Authorization that backs this subscription (owning side of the relationship).
     * Many-to-one: a single OAuth2 authorization is the aggregate root for one or two
     * subscriptions — an Energy subscription (via {@code authorizations.resource_uri}) and,
     * when the grant includes Customer/PII scope, a Customer subscription (via
     * {@code authorizations.customer_resource_uri}).
     *
     * <p>NOT NULL: a subscription has no independent lifecycle — it is created and removed only
     * through its authorization. Cascade is DETACH only; the inverse delete cascade lives on
     * {@link AuthorizationEntity#getSubscriptions()} (and the DB FK ON DELETE CASCADE).</p>
     */
    @ManyToOne(cascade = CascadeType.DETACH, fetch = FetchType.LAZY)
    @JoinColumn(name = "authorization_id", nullable = false)
    @NotNull
    private AuthorizationEntity authorization;

    /**
     * Application information for the subscribed application.
     * Identifies which third-party application has access.
     */
    @ManyToOne(cascade = CascadeType.DETACH, fetch = FetchType.LAZY)
    @JoinColumn(name = "application_information_id")
    @NotNull
    private ApplicationInformationEntity applicationInformation;

    /**
     * Usage points included in this subscription.
     * Many-to-many relationship allowing selective data access.
     */
    @ManyToMany(cascade = CascadeType.DETACH, fetch = FetchType.LAZY)
    @JoinTable(
        name = "subscription_usage_points",
        joinColumns = @JoinColumn(name = "subscription_id"),
        inverseJoinColumns = @JoinColumn(name = "usage_point_id")
    )
    private List<UsagePointEntity> usagePoints = new ArrayList<>();

    /**
     * Constructor with UUID.
     * UUID5 should be generated by EspiIdGeneratorService.generateSubscriptionId().
     *
     * @param id the UUID5 identifier (must be provided, not generated here)
     */
    public SubscriptionEntity(UUID id) {
        this.id = id;
    }

    /**
     * Constructor with basic subscription information.
     * Note: ID must be set separately using UUID5 from EspiIdGeneratorService.
     *
     * @param retailCustomer the customer who owns the subscription
     * @param applicationInformation the application accessing the data
     */
    public SubscriptionEntity(RetailCustomerEntity retailCustomer, ApplicationInformationEntity applicationInformation) {
        this.retailCustomer = retailCustomer;
        this.applicationInformation = applicationInformation;
    }

    /**
     * Gets a string representation of the ID for href generation.
     *
     * @return string representation of the UUID
     */
    public String getHashedId() {
        // Return the explicit hashedId if set, otherwise use UUID string
        return hashedId != null ? hashedId : (id != null ? id.toString() : null);
    }

    /**
     * Checks if this subscription is active.
     * A subscription is active if it has an active authorization.
     *
     * @return true if subscription is active, false otherwise
     */
    public boolean isActive() {
        return authorization != null && authorization.isActive();
    }

    /**
     * Checks if this subscription has expired.
     * A subscription is expired if its authorization has expired.
     *
     * @return true if subscription is expired, false otherwise
     */
    public boolean isExpired() {
        return authorization != null && authorization.isExpired();
    }

    /**
     * Checks if this subscription is revoked.
     * A subscription is revoked if its authorization is revoked.
     *
     * @return true if subscription is revoked, false otherwise
     */
    public boolean isRevoked() {
        return authorization != null && authorization.isRevoked();
    }

    /**
     * Gets the number of usage points in this subscription.
     *
     * @return count of usage points
     */
    public int getUsagePointCount() {
        return usagePoints != null ? usagePoints.size() : 0;
    }

    /**
     * Checks if this subscription includes the specified usage point.
     *
     * @param usagePoint the usage point to check
     * @return true if included, false otherwise
     */
    public boolean includesUsagePoint(UsagePointEntity usagePoint) {
        return usagePoints != null && usagePoints.contains(usagePoint);
    }

    /**
     * Gets the subscription ID from a resource URI.
     * Extracts the ID from URI patterns like "/espi/1_1/resource/Subscription/{id}".
     *
     * @param resourceURI the resource URI
     * @return subscription ID, or null if not found
     */
    public static String getSubscriptionIdFromUri(String resourceURI) {
        if (resourceURI == null || resourceURI.trim().isEmpty()) {
            return null;
        }
        String[] pieces = resourceURI.split("/");
        return pieces.length > 0 ? pieces[pieces.length - 1] : null;
    }

    /**
     * Checks if this subscription belongs to the specified customer.
     *
     * @param customerId the customer ID to check
     * @return true if belongs to customer, false otherwise
     */
    public boolean belongsToCustomer(Long customerId) {
        return retailCustomer != null && customerId != null &&
               customerId.equals(retailCustomer.getId());
    }

    /**
     * Pre-persist callback to validate required fields.
     * UUID5 must be set by the service layer before persisting.
     *
     * @throws IllegalStateException if ID is not set
     */
    @PrePersist
    protected void onCreate() {
        if (id == null) {
            throw new IllegalStateException(
                "Subscription ID must be set using EspiIdGeneratorService.generateSubscriptionId() before persisting");
        }
    }

    @Override
    public final boolean equals(Object o) {
        if (this == o) return true;
        if (o == null) return false;
        Class<?> oEffectiveClass = o instanceof HibernateProxy ? ((HibernateProxy) o).getHibernateLazyInitializer().getPersistentClass() : o.getClass();
        Class<?> thisEffectiveClass = this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass() : this.getClass();
        if (thisEffectiveClass != oEffectiveClass) return false;
        SubscriptionEntity that = (SubscriptionEntity) o;
        return getId() != null && Objects.equals(getId(), that.getId());
    }

    @Override
    public final int hashCode() {
        return this instanceof HibernateProxy ? ((HibernateProxy) this).getHibernateLazyInitializer().getPersistentClass().hashCode() : getClass().hashCode();
    }

    @Override
    public String toString() {
        return getClass().getSimpleName() + "(" +
                "id = " + getId() + ", " +
                "hashedId = " + getHashedId() + ")";
    }
}
